pipeline {

    agent any

    environment {
        DOCKER_USER = 'naneishwesinhlaing'
        IMAGE_NAME = 'todo-app'
        DOCKER_CREDS = 'docker-hub-credentials'
    }

    stages {

        stage('Build') {
            steps {
                sh 'npm install'
            }
        }

        stage('Containerize') {
            steps {
                sh "docker build -t ${DOCKER_USER}/${IMAGE_NAME}:latest ."
            }
        }

        stage('Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDS}", usernameVariable: 'USER', passwordVariable: 'PASS')]) {

                    sh "echo \$PASS | docker login -u \$USER --password-stdin"

                    sh "docker push ${DOCKER_USER}/${IMAGE_NAME}:latest"
                }
            }
        }

    }
}
